Lish is a command line shell written in Common Lisp. It is a non-POSIX shell,
and can also be used a Lisp REPL.

* Installing
** Install a binary
*** Pick one from the binary release page. [LINK NEEDED]
*** Put it somewhere in your path.
** Build from source
   This only works on unix-like systems.
   : git clone https://github.com/nibbula/yew.git
   : cd yew/lish
   : sh build.sh
*** For Windows
    Building is quite possible, but we don't currently have a simple build
    solution. (see windows.org)
** Loading without the build script
*** Loading
**** Install quicklisp from https://quicklisp.org if you don't already have it.
**** Install lish & some dependencies into local-projects
#+BEGIN_SRC shell
   cd ~/quicklisp/local-projects
   git clone https://github.com/nibbula/yew.git
#+END_SRC shell

**** In your Lisp, use quicklisp to load Lish:
#+BEGIN_SRC lisp
   (ql:quickload :lish)
#+END_SRC

**** Dependencies
     see dependencies.org
*** Building an executable
    The easiest way is to use the build script. But if you don't want to,
    another way is:

#+BEGIN_SRC lisp
  (lish:make-standlone)
#+END_SRC

    This should make an executable named "lish" in your current directory.
    Put it wherevere you'd like.

    Alternatively, you should be able to use:
#+BEGIN_SRC lisp
  (asdf:operate 'asdf:program-op :lish)
#+END_SRC

    Which will likely put an executable in whatever
    `(asdf:apply-output-translations "lish")` returns.

* Running
  From another shell:
#+BEGIN_SRC shell
  lish
#+END_SRC
  Or from a Lisp REPL:
#+BEGIN_SRC lisp
  (lish:lish)
#+END_SRC
* Using
  Lish is a combination of a Unix shell and Common Lisp REPL. As you might
  expect, it allows you to both type Unix commands and evaluate Lisp
  expressions. It tries to do so in way that would not be too annoying to
  someone familiar with either one.

** Examples of features
*** Familiar Unix style command pipelines
    : > ls
*** In-line Lisp evaluation
*** Lisp function pipelines
*** Object pipelines
*** Interactive features [animated gifs or whatever]
**** Command completion
**** Lisp completion
**** File completion
**** Help button
**** History searching
**** Easy prompts
**** Themes
**** Character picker
**** List choosing
**** Table broweer


* *WARNING*

Lish is full of bugs! It has not been tested. It will probably delete your
files. Lish is also very incomplete. It will certainly change in incompatible
ways. It should only be used for experimental purposes.
